kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "emulator-android-chart.fullname" . }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ template "emulator-android-chart.fullname" . }}-device
  template:
    metadata:
      labels:
        app: {{ template "emulator-android-chart.fullname" . }}-device
        affinity-key: emulator-device
    spec:
      volumes:
        - name: kvm
          hostPath:
            path: /dev/kvm
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: affinity-key
                    operator: In
                    values:
                      - emulator-device
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: device
          image: budtmo/docker-android-x86-8.1
          securityContext:
            privileged: true
          env:
            - name: DEVICE
              value: "Nexus 5"
            - name: AVD_NAME
              value: "{{ .Release.Name }}"
            - name: CONNECT_TO_GRID
              value: "true"
            - name: APPIUM
              value: "true"
            - name: AUTO_RECORD
              value: "false"
            - name: RELAXED_SECURITY
              value: "true"
            - name: SELENIUM_HOST
              value: {{ .Values.SeleniumGrid.SeleniumHub.Name }}-selenium-hub.{{ .Release.Namespace }}.svc.{{ .Values.Cluster.dns_suffix }}
          volumeMounts:
              - name: kvm
                mountPath: "/dev/kvm"


---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "emulator-android-chart.fullname" . }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ template "emulator-android-chart.fullname" . }}-device
  ports:
    - port: 6080
      targetPort: 6080
      name: vnc

