kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "multi-android-chart.fullname" . }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ template "multi-android-chart.fullname" . }}-device
  template:
    metadata:
      labels:
        app: {{ template "multi-android-chart.fullname" . }}-device
    spec:
      volumes:
          - name: kvm
            hostPath:
              path: /dev/kvm
      containers:
        - name: device
          image: budtmo/docker-android-x86-8.1
          #image: dev-registry.deez.re/techqa/dockerdroid:blo
          securityContext:
            privileged: true
          env:
            - name: DEVICE
              value: "Nexus 5"
            - name: AVD_NAME
              value: "{{ .Release.Name }}"
            - name: CONNECT_TO_GRID
              value: "true"
            - name: APPIUM
              value: "true"
            - name: AUTO_RECORD
              value: "false"
            - name: RELAXED_SECURITY
              value: "true"
            - name: SELENIUM_HOST
              value: {{ template "selenium.hub" . }}
          volumeMounts:
              - name: kvm
                mountPath: "/dev/kvm"
          #resources:
          #  limits:
          #    cpu: 1
          #    memory: 4Gi

---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "multi-android-chart.fullname" . }}-device
spec:
  type: NodePort
  selector:
    app: {{ template "multi-android-chart.fullname" . }}-device
  ports:
    - port: 6080
      targetPort: 6080
      name: vnc

